// <auto-generated />
using System;
using FlightBookingService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightBookingService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220609175457_FlightInits")]
    partial class FlightInits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightBookingService.Models.AirlineDetail", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirlineLogo");

                    b.Property<string>("AirlineName");

                    b.Property<string>("ContactAddress");

                    b.Property<string>("ContactNumber");

                    b.Property<bool>("IsBlocked");

                    b.HasKey("AirlineId");

                    b.ToTable("AirlineDetail");
                });

            modelBuilder.Entity("FlightBookingService.Models.BookingDetail", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookingDate");

                    b.Property<string>("Email");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<int>("FlightNumber");

                    b.Property<string>("FromPlace");

                    b.Property<int>("InventoryId");

                    b.Property<string>("Meal");

                    b.Property<int>("NoOfPassenger");

                    b.Property<string>("PNR");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<double>("TicketCharges");

                    b.Property<string>("ToPlace");

                    b.Property<string>("TravelClass");

                    b.Property<string>("UserName");

                    b.HasKey("BookingId");

                    b.HasIndex("InventoryId");

                    b.ToTable("BookingDetail");
                });

            modelBuilder.Entity("FlightBookingService.Models.InventoryDetail", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirlineId");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<int>("FlightNumber");

                    b.Property<string>("FromPlace");

                    b.Property<string>("Instrument");

                    b.Property<string>("Meal");

                    b.Property<int>("NoOfBusinessSeats");

                    b.Property<int>("NoOfNonBusinessSeats");

                    b.Property<int>("NoOfRows");

                    b.Property<string>("ScheduledDays");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<double>("TicketCharges");

                    b.Property<string>("ToPlace");

                    b.HasKey("InventoryId");

                    b.HasIndex("AirlineId");

                    b.ToTable("InventoryDetail");
                });

            modelBuilder.Entity("FlightBookingService.Models.PassengerDetail", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<int>("BookingId");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<int>("SeatNo");

                    b.HasKey("Pid");

                    b.HasIndex("BookingId");

                    b.ToTable("PassengerDetail");
                });

            modelBuilder.Entity("FlightBookingService.Models.BookingDetail", b =>
                {
                    b.HasOne("FlightBookingService.Models.InventoryDetail", "InventoryDetail")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FlightBookingService.Models.InventoryDetail", b =>
                {
                    b.HasOne("FlightBookingService.Models.AirlineDetail", "AirlineDetail")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FlightBookingService.Models.PassengerDetail", b =>
                {
                    b.HasOne("FlightBookingService.Models.BookingDetail", "BookingDetail")
                        .WithMany("PassengerDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
