// <auto-generated />
using System;
using FlightBookingService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightBookingService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220602164241_FlightBookingService")]
    partial class FlightBookingService
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightBookingService.Models.BookingDetail", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirlineId");

                    b.Property<DateTime>("BookingDate");

                    b.Property<string>("Email");

                    b.Property<DateTime>("EndDateTime");

                    b.Property<int>("FlightNumber");

                    b.Property<string>("FromPlace");

                    b.Property<int>("InventoryId");

                    b.Property<string>("Meal");

                    b.Property<int>("NoOfPassenger");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<double>("TicketCharges");

                    b.Property<string>("ToPlace");

                    b.Property<string>("TravelClass");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("BookingId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("FlightBookingService.Models.PassengerDetail", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<int>("BookingId");

                    b.Property<string>("Gender");

                    b.Property<int>("Name");

                    b.Property<int>("SeatNo");

                    b.HasKey("Pid");

                    b.HasIndex("BookingId");

                    b.ToTable("PassengerDetail");
                });

            modelBuilder.Entity("FlightBookingService.Models.PassengerDetail", b =>
                {
                    b.HasOne("FlightBookingService.Models.BookingDetail")
                        .WithMany("PassengerDetail")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
