// <auto-generated />
using System;
using FlightBookingService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightBookingService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightBookingService.Models.BookingDetail", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookingDate");

                    b.Property<string>("Destination");

                    b.Property<string>("Email");

                    b.Property<int>("Id");

                    b.Property<bool>("IsMeal");

                    b.Property<string>("Name");

                    b.Property<int>("NoOfPassenger");

                    b.Property<string>("PreferredCarrier");

                    b.Property<string>("Remarks");

                    b.Property<string>("Source");

                    b.Property<string>("TravelClass");

                    b.Property<DateTime>("TravellingDate");

                    b.HasKey("BookingId");

                    b.ToTable("BookingDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
